import { MigrationInterface, QueryRunner } from "typeorm";

export class AddOrderCodePrefixAndCounter1788924516323 implements MigrationInterface {
    name = 'AddOrderCodePrefixAndCounter1788924516323'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT IF EXISTS "FK_vehicle_hub"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT IF EXISTS "FK_39e4979ccbde8ee0b28bdc93b55"`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT IF EXISTS "FK_trip_order"`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT IF EXISTS "FK_584bd5d2f58af36ee11a9b8301b"`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT IF EXISTS "FK_trip_vehicle"`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT IF EXISTS "FK_b0febc31445a349db8313fca453"`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT IF EXISTS "FK_trip_driver"`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT IF EXISTS "FK_2034f2f2e58179b42c4866f6f13"`);
        await queryRunner.query(`ALTER TABLE "file" DROP CONSTRAINT IF EXISTS "FK_file_createdBy_user"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT IF EXISTS "FK_user_hub"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT IF EXISTS "FK_126cdfc5f79e8069cd41c6b4081"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT IF EXISTS "FK_session_user"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT IF EXISTS "FK_3d2f174ef04fb312fdebd0ddc53"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT IF EXISTS "FK_order_originHub"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT IF EXISTS "FK_87ddf48e09d6388d06e78a02c8f"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT IF EXISTS "FK_order_destinationHub"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT IF EXISTS "FK_c70f4c67cf2d76612253a909723"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_hub_code"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_aea1301f7ca5abfd7270533d4c"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_hub_isActive"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_e243dffd0af93bb696c42a7afa"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_vehicle_hubId"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_39e4979ccbde8ee0b28bdc93b5"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_trip_orderId"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_584bd5d2f58af36ee11a9b8301b"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_584bd5d2f58af36ee11a9b8301"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_trip_status"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_c2fe26a773051b54ac1246cdfa"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_user_username"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_78a916df40e02a9deb1c4b75ed"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_session_userId"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_3d2f174ef04fb312fdebd0ddc5"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_order_orderCode"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_cee790b609c1fcf83f3345d964"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_order_status"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_7a9573d6a1fb982772a9123320"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_notification_userId"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_1ced25315eb974b73391fb1c81"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_notification_userId_isRead"`);
        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "order_code_counter" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "id" SERIAL NOT NULL, "hubId" integer NOT NULL, "operatorInitials" character varying(10) NOT NULL, "yearMonth" character varying(6) NOT NULL, "lastSequence" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_18246c841e5ea57195a1ee16932" UNIQUE ("hubId", "operatorInitials", "yearMonth"), CONSTRAINT "PK_474e83b47c090070ccb1b161a19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_eec5a404fa3b168adb1950c8c7" ON "order_code_counter" ("hubId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_cad0e2b8a87ccdb55e0405da53" ON "order_code_counter" ("operatorInitials") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_96f88986e3bfb23a4ecc2d9c8e" ON "order_code_counter" ("yearMonth") `);
        await queryRunner.query(`ALTER TABLE "file" DROP COLUMN IF EXISTS "createdAt"`);
        await queryRunner.query(`ALTER TABLE "file" DROP COLUMN IF EXISTS "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "file" DROP COLUMN IF EXISTS "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "hub" ADD COLUMN IF NOT EXISTS "orderCodePrefix" character varying`);
        await queryRunner.query(`ALTER TABLE "hub" DROP CONSTRAINT IF EXISTS "UQ_2f951a5c8a2a7a378244226fc11"`);
        await queryRunner.query(`ALTER TABLE "hub" ADD CONSTRAINT "UQ_2f951a5c8a2a7a378244226fc11" UNIQUE ("orderCodePrefix")`);
        await queryRunner.query(`ALTER TABLE "hub" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hub" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "trip" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "trip" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_aea1301f7ca5abfd7270533d4c" ON "hub" ("code") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_2f951a5c8a2a7a378244226fc1" ON "hub" ("orderCodePrefix") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_e243dffd0af93bb696c42a7afa" ON "hub" ("isActive") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_39e4979ccbde8ee0b28bdc93b5" ON "vehicle" ("hubId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_584bd5d2f58af36ee11a9b8301" ON "trip" ("orderId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_c2fe26a773051b54ac1246cdfa" ON "trip" ("status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_78a916df40e02a9deb1c4b75ed" ON "user" ("username") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_3d2f174ef04fb312fdebd0ddc5" ON "session" ("userId") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_cee790b609c1fcf83f3345d964" ON "order" ("orderCode") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_7a9573d6a1fb982772a9123320" ON "order" ("status") `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_1ced25315eb974b73391fb1c81" ON "notification" ("userId") `);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT IF EXISTS "FK_39e4979ccbde8ee0b28bdc93b55"`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_39e4979ccbde8ee0b28bdc93b55" FOREIGN KEY ("hubId") REFERENCES "hub"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT IF EXISTS "FK_584bd5d2f58af36ee11a9b8301b"`);
        await queryRunner.query(`ALTER TABLE "trip" ADD CONSTRAINT "FK_584bd5d2f58af36ee11a9b8301b" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT IF EXISTS "FK_b0febc31445a349db8313fca453"`);
        await queryRunner.query(`ALTER TABLE "trip" ADD CONSTRAINT "FK_b0febc31445a349db8313fca453" FOREIGN KEY ("vehicleId") REFERENCES "vehicle"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT IF EXISTS "FK_2034f2f2e58179b42c4866f6f13"`);
        await queryRunner.query(`ALTER TABLE "trip" ADD CONSTRAINT "FK_2034f2f2e58179b42c4866f6f13" FOREIGN KEY ("driverId") REFERENCES "driver"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT IF EXISTS "FK_126cdfc5f79e8069cd41c6b4081"`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_126cdfc5f79e8069cd41c6b4081" FOREIGN KEY ("hubId") REFERENCES "hub"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT IF EXISTS "FK_3d2f174ef04fb312fdebd0ddc53"`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_3d2f174ef04fb312fdebd0ddc53" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT IF EXISTS "FK_87ddf48e09d6388d06e78a02c8f"`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_87ddf48e09d6388d06e78a02c8f" FOREIGN KEY ("originHubId") REFERENCES "hub"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT IF EXISTS "FK_c70f4c67cf2d76612253a909723"`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_c70f4c67cf2d76612253a909723" FOREIGN KEY ("destinationHubId") REFERENCES "hub"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_c70f4c67cf2d76612253a909723"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_87ddf48e09d6388d06e78a02c8f"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_3d2f174ef04fb312fdebd0ddc53"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_126cdfc5f79e8069cd41c6b4081"`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT "FK_2034f2f2e58179b42c4866f6f13"`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT "FK_b0febc31445a349db8313fca453"`);
        await queryRunner.query(`ALTER TABLE "trip" DROP CONSTRAINT "FK_584bd5d2f58af36ee11a9b8301b"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_39e4979ccbde8ee0b28bdc93b55"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ced25315eb974b73391fb1c81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a9573d6a1fb982772a9123320"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee790b609c1fcf83f3345d964"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d2f174ef04fb312fdebd0ddc5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78a916df40e02a9deb1c4b75ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2fe26a773051b54ac1246cdfa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_584bd5d2f58af36ee11a9b8301"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39e4979ccbde8ee0b28bdc93b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e243dffd0af93bb696c42a7afa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f951a5c8a2a7a378244226fc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aea1301f7ca5abfd7270533d4c"`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notification" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "order" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "trip" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "trip" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "hub" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "hub" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "hub" DROP CONSTRAINT "UQ_2f951a5c8a2a7a378244226fc11"`);
        await queryRunner.query(`ALTER TABLE "hub" DROP COLUMN "orderCodePrefix"`);
        await queryRunner.query(`ALTER TABLE "file" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "file" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "file" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96f88986e3bfb23a4ecc2d9c8e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cad0e2b8a87ccdb55e0405da53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eec5a404fa3b168adb1950c8c7"`);
        await queryRunner.query(`DROP TABLE "order_code_counter"`);
        await queryRunner.query(`CREATE INDEX "IDX_notification_userId_isRead" ON "notification" ("isRead", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_notification_userId" ON "notification" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_order_status" ON "order" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_order_orderCode" ON "order" ("orderCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_session_userId" ON "session" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_username" ON "user" ("username") `);
        await queryRunner.query(`CREATE INDEX "IDX_trip_status" ON "trip" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_trip_orderId" ON "trip" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_vehicle_hubId" ON "vehicle" ("hubId") `);
        await queryRunner.query(`CREATE INDEX "IDX_hub_isActive" ON "hub" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_hub_code" ON "hub" ("code") `);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_order_destinationHub" FOREIGN KEY ("destinationHubId") REFERENCES "hub"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_order_originHub" FOREIGN KEY ("originHubId") REFERENCES "hub"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_session_user" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_user_hub" FOREIGN KEY ("hubId") REFERENCES "hub"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file" ADD CONSTRAINT "FK_file_createdBy_user" FOREIGN KEY ("createdBy") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip" ADD CONSTRAINT "FK_trip_driver" FOREIGN KEY ("driverId") REFERENCES "driver"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip" ADD CONSTRAINT "FK_trip_vehicle" FOREIGN KEY ("vehicleId") REFERENCES "vehicle"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip" ADD CONSTRAINT "FK_trip_order" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_vehicle_hub" FOREIGN KEY ("hubId") REFERENCES "hub"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
