import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { HubEntity } from '../../../../hubs/infrastructure/persistence/relational/entities/hub.entity';

@Injectable()
export class HubSeedService {
  constructor(
    @InjectRepository(HubEntity)
    private readonly repository: Repository<HubEntity>,
  ) {}

  async run() {
    const seedHubs = [
      // ── Hub Cấp 1 (Main Hubs) ──
      {
        code: 'HUB-HCM-01',
        legacyCodes: ['HUB-SGN-01'],
        name: 'Andromeda Hub - HCM',
        city: 'TP. Hồ Chí Minh',
        address: 'Khu Công Nghệ Cao, TP. Thủ Đức, TP. Hồ Chí Minh',
        contactPhone: '028-3736-8888',
        managerName: 'Lê Hoàng Nam',
        isActive: true,
      },
      {
        code: 'HUB-DAD-01',
        legacyCodes: ['HUB-DAD-01'],
        name: 'Magellan Hub - Đà Nẵng',
        city: 'Đà Nẵng',
        address: 'KCN Hòa Khánh, Quận Liên Chiểu, TP. Đà Nẵng',
        contactPhone: '0236-3732-555',
        managerName: 'Trần Đình Kho',
        isActive: true,
      },
      {
        code: 'HUB-HYN-01',
        legacyCodes: ['HUB-HAN-01'],
        name: 'Polaris Hub - Hưng Yên',
        city: 'Hưng Yên',
        address: 'KCN Thăng Long II, Huyện Mỹ Hào, Tỉnh Hưng Yên',
        contactPhone: '0221-3974-888',
        managerName: 'Nguyễn Văn Quản',
        isActive: true,
      },
      // ── Hub Cấp 2 (34 Tuyến Xe Bo ứng với 34 Tỉnh Thành Việt Nam sau sắp xếp 1/7/2025-2026) ──
      // 6 Thành phố trực thuộc Trung ương
      {
        code: 'HUB-BO-HCM-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến HCM',
        city: 'TP. Hồ Chí Minh',
        address: 'Điểm trung chuyển phân tán TP. Hồ Chí Minh',
        contactPhone: '028-3736-9999',
        managerName: 'Tài Xế Bo HCM',
        isActive: true,
      },
      {
        code: 'HUB-BO-HAN-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Hà Nội',
        city: 'TP. Hà Nội',
        address: 'Điểm trung chuyển phân tán TP. Hà Nội',
        contactPhone: '024-3836-9999',
        managerName: 'Tài Xế Bo Hà Nội',
        isActive: true,
      },
      {
        code: 'HUB-BO-DAD-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Đà Nẵng',
        city: 'Đà Nẵng',
        address: 'Điểm trung chuyển phân tán Đà Nẵng',
        contactPhone: '0236-3732-999',
        managerName: 'Tài Xế Bo Đà Nẵng',
        isActive: true,
      },
      {
        code: 'HUB-BO-HPH-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Hải Phòng',
        city: 'TP. Hải Phòng',
        address: 'Điểm trung chuyển phân tán Hải Phòng',
        contactPhone: '0225-3888-999',
        managerName: 'Tài Xế Bo Hải Phòng',
        isActive: true,
      },
      {
        code: 'HUB-BO-CTH-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Cần Thơ',
        city: 'TP. Cần Thơ',
        address: 'Điểm trung chuyển phân tán Cần Thơ',
        contactPhone: '0292-3888-999',
        managerName: 'Tài Xế Bo Cần Thơ',
        isActive: true,
      },
      {
        code: 'HUB-BO-HUE-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Huế',
        city: 'TP. Huế',
        address: 'Điểm trung chuyển phân tán TP. Huế',
        contactPhone: '0234-3888-999',
        managerName: 'Tài Xế Bo Huế',
        isActive: true,
      },
      // 28 Tỉnh thành
      {
        code: 'HUB-BO-HYN-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Hưng Yên',
        city: 'Hưng Yên',
        address: 'Điểm trung chuyển phân tán Hưng Yên',
        contactPhone: '0221-3974-999',
        managerName: 'Tài Xế Bo Hưng Yên',
        isActive: true,
      },
      {
        code: 'HUB-BO-BNI-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Bắc Ninh',
        city: 'Bắc Ninh',
        address: 'Điểm trung chuyển phân tán Bắc Ninh',
        contactPhone: '0222-3888-999',
        managerName: 'Tài Xế Bo Bắc Ninh',
        isActive: true,
      },
      {
        code: 'HUB-BO-QNI-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Quảng Ninh',
        city: 'Quảng Ninh',
        address: 'Điểm trung chuyển phân tán Quảng Ninh',
        contactPhone: '0203-3888-999',
        managerName: 'Tài Xế Bo Quảng Ninh',
        isActive: true,
      },
      {
        code: 'HUB-BO-NBI-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Ninh Bình',
        city: 'Ninh Bình',
        address: 'Điểm trung chuyển phân tán Ninh Bình',
        contactPhone: '0229-3888-999',
        managerName: 'Tài Xế Bo Ninh Bình',
        isActive: true,
      },
      {
        code: 'HUB-BO-TNG-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Thái Nguyên',
        city: 'Thái Nguyên',
        address: 'Điểm trung chuyển phân tán Thái Nguyên',
        contactPhone: '0208-3888-999',
        managerName: 'Tài Xế Bo Thái Nguyên',
        isActive: true,
      },
      {
        code: 'HUB-BO-PTH-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Phú Thọ',
        city: 'Phú Thọ',
        address: 'Điểm trung chuyển phân tán Phú Thọ',
        contactPhone: '0210-3888-999',
        managerName: 'Tài Xế Bo Phú Thọ',
        isActive: true,
      },
      {
        code: 'HUB-BO-LCA-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Lào Cai',
        city: 'Lào Cai',
        address: 'Điểm trung chuyển phân tán Lào Cai',
        contactPhone: '0214-3888-999',
        managerName: 'Tài Xế Bo Lào Cai',
        isActive: true,
      },
      {
        code: 'HUB-BO-TQU-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Tuyên Quang',
        city: 'Tuyên Quang',
        address: 'Điểm trung chuyển phân tán Tuyên Quang',
        contactPhone: '0207-3888-999',
        managerName: 'Tài Xế Bo Tuyên Quang',
        isActive: true,
      },
      {
        code: 'HUB-BO-LSN-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Lạng Sơn',
        city: 'Lạng Sơn',
        address: 'Điểm trung chuyển phân tán Lạng Sơn',
        contactPhone: '0205-3888-999',
        managerName: 'Tài Xế Bo Lạng Sơn',
        isActive: true,
      },
      {
        code: 'HUB-BO-CBA-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Cao Bằng',
        city: 'Cao Bằng',
        address: 'Điểm trung chuyển phân tán Cao Bằng',
        contactPhone: '0206-3888-999',
        managerName: 'Tài Xế Bo Cao Bằng',
        isActive: true,
      },
      {
        code: 'HUB-BO-LCH-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Lai Châu',
        city: 'Lai Châu',
        address: 'Điểm trung chuyển phân tán Lai Châu',
        contactPhone: '0213-3888-999',
        managerName: 'Tài Xế Bo Lai Châu',
        isActive: true,
      },
      {
        code: 'HUB-BO-DBI-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Điện Biên',
        city: 'Điện Biên',
        address: 'Điểm trung chuyển phân tán Điện Biên',
        contactPhone: '0215-3888-999',
        managerName: 'Tài Xế Bo Điện Biên',
        isActive: true,
      },
      {
        code: 'HUB-BO-SLA-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Sơn La',
        city: 'Sơn La',
        address: 'Điểm trung chuyển phân tán Sơn La',
        contactPhone: '0212-3888-999',
        managerName: 'Tài Xế Bo Sơn La',
        isActive: true,
      },
      {
        code: 'HUB-BO-THO-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Thanh Hóa',
        city: 'Thanh Hóa',
        address: 'Điểm trung chuyển phân tán Thanh Hóa',
        contactPhone: '0237-3888-999',
        managerName: 'Tài Xế Bo Thanh Hóa',
        isActive: true,
      },
      {
        code: 'HUB-BO-NAN-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Nghệ An',
        city: 'Nghệ An',
        address: 'Điểm trung chuyển phân tán Nghệ An',
        contactPhone: '0238-3888-999',
        managerName: 'Tài Xế Bo Nghệ An',
        isActive: true,
      },
      {
        code: 'HUB-BO-HTI-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Hà Tĩnh',
        city: 'Hà Tĩnh',
        address: 'Điểm trung chuyển phân tán Hà Tĩnh',
        contactPhone: '0239-3888-999',
        managerName: 'Tài Xế Bo Hà Tĩnh',
        isActive: true,
      },
      {
        code: 'HUB-BO-QTR-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Quảng Trị',
        city: 'Quảng Trị',
        address: 'Điểm trung chuyển phân tán Quảng Trị',
        contactPhone: '0233-3888-999',
        managerName: 'Tài Xế Bo Quảng Trị',
        isActive: true,
      },
      {
        code: 'HUB-BO-QNG-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Quảng Ngãi',
        city: 'Quảng Ngãi',
        address: 'Điểm trung chuyển phân tán Quảng Ngãi',
        contactPhone: '0255-3888-999',
        managerName: 'Tài Xế Bo Quảng Ngãi',
        isActive: true,
      },
      {
        code: 'HUB-BO-GLA-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Gia Lai',
        city: 'Gia Lai',
        address: 'Điểm trung chuyển phân tán Gia Lai',
        contactPhone: '0269-3888-999',
        managerName: 'Tài Xế Bo Gia Lai',
        isActive: true,
      },
      {
        code: 'HUB-BO-KHO-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Khánh Hòa',
        city: 'Khánh Hòa',
        address: 'Điểm trung chuyển phân tán Khánh Hòa',
        contactPhone: '0258-3888-999',
        managerName: 'Tài Xế Bo Khánh Hòa',
        isActive: true,
      },
      {
        code: 'HUB-BO-LDG-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Lâm Đồng',
        city: 'Lâm Đồng',
        address: 'Điểm trung chuyển phân tán Lâm Đồng',
        contactPhone: '0263-3888-999',
        managerName: 'Tài Xế Bo Lâm Đồng',
        isActive: true,
      },
      {
        code: 'HUB-BO-DLK-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Đắk Lắk',
        city: 'Đắk Lắk',
        address: 'Điểm trung chuyển phân tán Đắk Lắk',
        contactPhone: '0262-3888-999',
        managerName: 'Tài Xế Bo Đắk Lắk',
        isActive: true,
      },
      {
        code: 'HUB-BO-DNA-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Đồng Nai',
        city: 'Đồng Nai',
        address: 'Điểm trung chuyển phân tán Đồng Nai',
        contactPhone: '0251-3888-999',
        managerName: 'Tài Xế Bo Đồng Nai',
        isActive: true,
      },
      {
        code: 'HUB-BO-TNI-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Tây Ninh',
        city: 'Tây Ninh',
        address: 'Điểm trung chuyển phân tán Tây Ninh',
        contactPhone: '0276-3888-999',
        managerName: 'Tài Xế Bo Tây Ninh',
        isActive: true,
      },
      {
        code: 'HUB-BO-DTH-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Đồng Tháp',
        city: 'Đồng Tháp',
        address: 'Điểm trung chuyển phân tán Đồng Tháp',
        contactPhone: '0277-3888-999',
        managerName: 'Tài Xế Bo Đồng Tháp',
        isActive: true,
      },
      {
        code: 'HUB-BO-VLO-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Vĩnh Long',
        city: 'Vĩnh Long',
        address: 'Điểm trung chuyển phân tán Vĩnh Long',
        contactPhone: '0270-3888-999',
        managerName: 'Tài Xế Bo Vĩnh Long',
        isActive: true,
      },
      {
        code: 'HUB-BO-AGI-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến An Giang',
        city: 'An Giang',
        address: 'Điểm trung chuyển phân tán An Giang',
        contactPhone: '0296-3888-999',
        managerName: 'Tài Xế Bo An Giang',
        isActive: true,
      },
      {
        code: 'HUB-BO-CMA-01',
        legacyCodes: [],
        name: 'Xe bo Tuyến Cà Mau',
        city: 'Cà Mau',
        address: 'Điểm trung chuyển phân tán Cà Mau',
        contactPhone: '0290-3888-999',
        managerName: 'Tài Xế Bo Cà Mau',
        isActive: true,
      },
    ];

    for (const h of seedHubs) {
      const searchConditions: Array<{ code?: string; name?: string }> = [
        { code: h.code },
        ...(h.legacyCodes || []).map((lc: string) => ({
          code: lc,
        })),
        { name: h.name },
      ];

      const existing = await this.repository.findOne({
        where: searchConditions,
      });

      if (existing) {
        existing.code = h.code;
        existing.name = h.name;
        existing.city = h.city;
        existing.address = h.address;
        existing.contactPhone = h.contactPhone;
        existing.managerName = h.managerName;
        existing.isActive = h.isActive;
        await this.repository.save(existing);
      } else {
        await this.repository.save(
          this.repository.create({
            code: h.code,
            name: h.name,
            city: h.city,
            address: h.address,
            contactPhone: h.contactPhone,
            managerName: h.managerName,
            isActive: h.isActive,
          }),
        );
      }
    }
  }
}
